name: KUHUL Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build llvm
        run: ./bootstrap.sh
      - name: build kuhul
        run: ./build.sh
